---
language: python
python: 3.5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz
  - pip install --upgrade pip
  - pip install iso8601
  - pip install -r requirements.txt

script:
  - python doc/src/test/*

after_success:
  - find doc/src -type f -name '*.py' -exec pep8 {} \;
  - make -C doc/dot
