---
language: python
python: 3.5

# blacklist branches from activating travis-ci builds
branches:
  except:
    - diagrams

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz
  - pip install --upgrade pip
  - pip install iso8601
  - pip install -r requirements.txt

script:
  - python doc/src/test/*
  - find doc/src -type f -name '*.py' -exec pep8 {} \;
  - make -C doc/dot

after_success:
  - mkdir $HOME/diagrams && cp -fv doc/dot/*.png $HOME/diagrams
  - bin/hook-travis-publish-diagrams.sh

env:
  global:
    - GH_REF: github.com/ericcrosson/auto.git
