---
language: python
python: 3.5

before_install:
  - pip install --upgrade pip
  - pip install iso8601
  - pip install -r requirements.txt

script:
  - python src/test/*

after_success:
  - find . -type f -name '*.py' -exec pep8 {} \;
